language: go

os:
  - linux

go:
  - 1.8

addons:
    code_climate:
        repo_token: 81a41351c4a25caf81fbd1ba3c558eac13fc70c64119a7d7c3541e572192ce24

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go install github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
